#!/usr/bin/env bash
# The vendored sqflite worker must match the package version its client speaks.
#
#   ./scripts/check-sqflite-provenance.sh
#
# flutter/web/sqflite_sw.js is 264KB of compiled Dart, committed so a deploy
# does not depend on a build-time fetch. The client that talks to it is
# compiled into main.dart.js from whatever `sqflite_common_ffi_web` resolves
# to. pubspec.yaml pins a caret range, so `flutter pub upgrade` can move the
# client to any 1.x while the committed worker stays frozen — and the worker
# carries no version marker, so nothing about the file would look wrong.
#
# Three failures this catches:
#
#   1. `flutter pub upgrade` moved the resolved package and nobody re-ran
#      `dart run sqflite_common_ffi_web:setup`. pubspec.lock and the recorded
#      version disagree; this is the one the issue (#256) is about.
#   2. Somebody edited the recorded version by hand to make (1) go away. The
#      package sha256 is a SECOND fact from the lock, and it still names the
#      release the worker actually came from.
#   3. A worker or wasm dropped in by hand — a local experiment, a partial
#      copy. The recorded hashes would not match the bytes.
#
# What it deliberately does NOT do is regenerate and compare, the way
# scripts/retro-wasm/build.sh --check does. The setup compiles the worker with
# the local dart2js, so the bytes depend on the Dart SDK as well as on the
# package, and CI takes Flutter's floating `stable` channel — a derived check
# would go red on an SDK release rather than on a real drift. See the note in
# flutter/web/sqflite_sw.version.
#
# Runs in CI (ubuntu) and locally (macOS); both hash tools are handled.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB="$HERE/../flutter/web"
LOCK="$HERE/../flutter/pubspec.lock"
PROV="$WEB/sqflite_sw.version"

fail() { echo "error: $*" >&2; exit 1; }

[ -f "$LOCK" ] || fail "flutter/pubspec.lock is missing"
[ -f "$PROV" ] || fail "flutter/web/sqflite_sw.version is missing — see the Storage section of ARCHITECTURE.md"
[ -f "$WEB/sqflite_sw.js" ] || fail "flutter/web/sqflite_sw.js is missing"
[ -f "$WEB/sqlite3.wasm" ] || fail "flutter/web/sqlite3.wasm is missing"

# Read one field out of the sqflite_common_ffi_web block in pubspec.lock.
# Bounded by the next top-level (two-space) key so a field from a neighbouring
# package can never be read as this one's — `sqflite_darwin` sits directly
# below it and has both a sha256 and a version. Quotes stripped
# unconditionally: pub quotes a scalar that would otherwise parse as a number,
# so "1.1.2" is quoted and a hash starting with a letter is not.
#
# The `sub(/\r$/, "")` is the lesson check-retro-provenance.sh records: on a
# CRLF checkout the trailing \r rides along, and here it would break BOTH the
# `$` anchor that finds the block and the values inside it — producing the
# useless "1.1.2 is not 1.1.2". Stripped from the whole line, before anything
# looks at it.
lock_field() {
  awk -v want="$1" '
    { sub(/\r$/, "") }
    /^  sqflite_common_ffi_web:$/ { in_block = 1; next }
    in_block && /^  [^ ]/ { in_block = 0 }
    in_block && $1 == want":" { v = $2; gsub(/["[:space:]]/, "", v); print v; exit }
  ' "$LOCK"
}

# `|| true` on every extraction so a pipeline exit status cannot end the script
# under `set -o pipefail` before fail() gets to say what is wrong — the retro
# script learned that one the hard way with an empty input and a wordless 141.
prov_field() {
  { awk -v want="$1" '$1 == want { print $2; exit }' "$PROV" || true; } | tr -d '[:space:]'
}

want_version="$(lock_field version || true)"
want_sha="$(lock_field sha256 || true)"
[ -n "$want_version" ] || fail "pubspec.lock has no resolved sqflite_common_ffi_web version — is the dependency still there?"
[ -n "$want_sha" ] || fail "pubspec.lock records no sha256 for sqflite_common_ffi_web"

got_version="$(prov_field version)"
got_sha="$(prov_field package-sha256)"
[ -n "$got_version" ] || fail "flutter/web/sqflite_sw.version records no version"
[ -n "$got_sha" ] || fail "flutter/web/sqflite_sw.version records no package-sha256"

regen="Regenerate the worker and re-record it:
         cd flutter && dart run sqflite_common_ffi_web:setup
       That rewrites web/sqflite_sw.js AND web/sqlite3.wasm; then update
       flutter/web/sqflite_sw.version (version, package-sha256, both hashes)."

if [ "$want_version" != "$got_version" ]; then
  fail "pubspec.lock resolves sqflite_common_ffi_web to $want_version but the
       committed worker was generated by $got_version.
       $regen"
fi

if [ "$want_sha" != "$got_sha" ]; then
  fail "sqflite_sw.version claims $got_version, and pubspec.lock agrees on the
       version — but the recorded package sha256 is not the one in the lock.
       recorded ${got_sha:0:16}…
       lock     ${want_sha:0:16}…
       The version line was probably edited without regenerating.
       $regen"
fi

sha256_of() {
  if command -v sha256sum >/dev/null; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

for f in sqflite_sw.js sqlite3.wasm; do
  want="$(prov_field "$f" | sed 's/^sha256://')"
  [ -n "$want" ] || fail "flutter/web/sqflite_sw.version records no sha256 for $f"
  got="$(sha256_of "$WEB/$f")"
  if [ "$want" != "$got" ]; then
    fail "flutter/web/$f does not match the sha256 recorded beside it.
       recorded ${want:0:16}…
       actual   ${got:0:16}…
       Whatever produced those bytes did not write its provenance.
       $regen"
  fi
done

echo "sqflite worker provenance ok: sqflite_common_ffi_web $got_version, worker $(sha256_of "$WEB/sqflite_sw.js" | cut -c1-16)…"
