// Audit the explanation layer's coverage against ground truth we didn't
// write: the lichess puzzle DB's theme tags were generated by cook.py, the
// same tagger explain.ts ports. For every puzzle in the stratified sample,
// run motifTags over each solver move and compare the union against the
// puzzle's themes.
//
// Three questions:
//   recall     — of puzzles cook.py tagged `fork`, how many do we tag fork?
//   coverage   — how often would explainGoodMove have SOMETHING to say
//                about the first solver move (any tag, incl. material)?
//   gaps       — which frequent themes have no detector at all?
//
//   npx tsx scripts/explain-audit.mts [--sample data/puzzles/sample.json]

import { readFileSync } from 'node:fs';
import { Chess } from 'chess.js';
import { motifTags, type Motif } from '../src/lib/engine/explain';

const argv = process.argv.slice(2);
function opt(name: string, dflt: string): string {
	const i = argv.indexOf(`--${name}`);
	return i >= 0 && argv[i + 1] ? argv[i + 1] : dflt;
}

interface Puzzle {
	id: string;
	fen: string;
	moves: string[]; // moves[0] = opponent setup; solver moves at odd indices
	rating: number;
	themes: string[];
}
const puzzles: Puzzle[] = JSON.parse(readFileSync(opt('sample', 'data/puzzles/sample.json'), 'utf8'));

// themes with a direct counterpart in our Motif vocabulary
const THEME_TO_MOTIF: Record<string, Motif> = {
	fork: 'fork',
	pin: 'pin',
	skewer: 'skewer',
	discoveredAttack: 'discovered attack',
	trappedPiece: 'trapped piece',
	hangingPiece: 'free capture',
	mate: 'mate'
};

// themes that describe the puzzle, not a detectable motif — excluded from the gap list
const META_THEMES = new Set([
	'opening', 'middlegame', 'endgame',
	'rookEndgame', 'pawnEndgame', 'queenEndgame', 'bishopEndgame', 'knightEndgame', 'queenRookEndgame',
	'short', 'long', 'veryLong', 'oneMove',
	'crushing', 'advantage', 'equality',
	'mateIn1', 'mateIn2', 'mateIn3', 'mateIn4', 'mateIn5', // roll up into 'mate'
	'master', 'masterVsMaster', 'superGM'
]);

function apply(c: Chess, uci: string) {
	return c.move({ from: uci.slice(0, 2), to: uci.slice(2, 4), promotion: uci[4] });
}

// Walk one puzzle: union of our tags across solver moves, plus first-move tags.
function tagPuzzle(p: Puzzle): { union: Set<Motif>; first: Motif[] } | null {
	const c = new Chess(p.fen);
	try {
		apply(c, p.moves[0]);
	} catch {
		return null;
	}
	// does the solution end in mate? then solver move i has mate-in-(remaining)
	const probe = new Chess(c.fen());
	let legal = true;
	for (let i = 1; i < p.moves.length; i++) {
		try {
			apply(probe, p.moves[i]);
		} catch {
			legal = false;
			break;
		}
	}
	const endsInMate = legal && probe.isCheckmate();

	const union = new Set<Motif>();
	let first: Motif[] = [];
	let solverIdx = 0; // 0-based count of solver moves seen
	for (let i = 1; i < p.moves.length; i++) {
		const isSolver = i % 2 === 1;
		if (isSolver) {
			const remainingSolver = Math.ceil((p.moves.length - i) / 2);
			const mate = endsInMate ? remainingSolver : null;
			const tags = motifTags(c.fen(), p.moves[i], p.moves.slice(i), mate);
			for (const t of tags) union.add(t);
			if (solverIdx === 0) first = tags;
			solverIdx++;
		}
		try {
			apply(c, p.moves[i]);
		} catch {
			return solverIdx > 0 ? { union, first } : null;
		}
	}
	return { union, first };
}

const BANDS: Array<[string, (r: number) => boolean]> = [
	['<1000', (r) => r < 1000],
	['1000-1599', (r) => r >= 1000 && r < 1600],
	['1600+', (r) => r >= 1600]
];

// tallies
interface Cell { n: number; hit: number }
interface Agree { n: number; themed: number; examples: string[] }
const recall = new Map<string, Map<string, Cell>>(); // theme → band → cell
const ourTagCount = new Map<Motif, Agree>(); // union across solver moves
const firstTagCount = new Map<Motif, Agree>(); // first solver move only
const themeFreq = new Map<string, number>();
let total = 0;
let skipped = 0;
let firstTagged = 0; // first solver move has ≥1 tag
let unthemedButTagged = 0; // no mapped theme, but we still found something
let unthemedTotal = 0;

for (const p of puzzles) {
	const res = tagPuzzle(p);
	if (!res) {
		skipped++;
		continue;
	}
	total++;
	const themes = new Set(p.themes);
	// roll mateIn* up into mate for the comparison
	if ([...themes].some((t) => t.startsWith('mateIn'))) themes.add('mate');
	for (const t of p.themes) themeFreq.set(t, (themeFreq.get(t) ?? 0) + 1);

	const band = BANDS.find(([, f]) => f(p.rating))![0];
	for (const [theme, motif] of Object.entries(THEME_TO_MOTIF)) {
		if (!themes.has(theme)) continue;
		let byBand = recall.get(theme);
		if (!byBand) recall.set(theme, (byBand = new Map()));
		for (const b of [band, 'all']) {
			let cell = byBand.get(b);
			if (!cell) byBand.set(b, (cell = { n: 0, hit: 0 }));
			cell.n++;
			if (res.union.has(motif)) cell.hit++;
		}
	}
	// precision-ish: when WE tag a motif, does cook.py agree? Tallied two ways:
	// union across solver moves (upper bound on firing) and first-move-only
	// (what practice tagging and explainGoodMove actually surface).
	for (const [map, tags] of [
		[ourTagCount, [...res.union]],
		[firstTagCount, res.first]
	] as const) {
		for (const motif of tags) {
			let c = map.get(motif);
			if (!c) map.set(motif, (c = { n: 0, themed: 0, examples: [] }));
			c.n++;
			const theme = Object.entries(THEME_TO_MOTIF).find(([, m]) => m === motif)?.[0];
			if (theme && themes.has(theme)) c.themed++;
			else if (map === firstTagCount && c.examples.length < 3) c.examples.push(p.id);
		}
	}
	if (res.first.length > 0) firstTagged++;
	const hasMappedTheme = Object.keys(THEME_TO_MOTIF).some((t) => themes.has(t));
	if (!hasMappedTheme) {
		unthemedTotal++;
		if (res.first.length > 0) unthemedButTagged++;
	}
}

const pct = (a: number, b: number) => (b === 0 ? '   —' : `${((100 * a) / b).toFixed(0).padStart(3)}%`);

console.log(`${total} puzzles audited (${skipped} skipped: illegal replay)\n`);

console.log('RECALL vs cook.py themes (did we tag what lichess tagged?)');
console.log(`  ${'theme'.padEnd(18)} ${'all'.padStart(12)} ${'<1000'.padStart(12)} ${'1000-1599'.padStart(12)} ${'1600+'.padStart(12)}`);
for (const [theme] of Object.entries(THEME_TO_MOTIF)) {
	const byBand = recall.get(theme);
	if (!byBand) continue;
	const cells = ['all', ...BANDS.map(([b]) => b)].map((b) => {
		const c = byBand.get(b);
		return c ? `${pct(c.hit, c.n)} (${c.n})`.padStart(12) : '—'.padStart(12);
	});
	console.log(`  ${theme.padEnd(18)} ${cells.join(' ')}`);
}

console.log('\nAGREEMENT when we tag (does cook.py carry the matching theme?)');
console.log(`  ${'motif'.padEnd(18)} ${'union'.padStart(16)} ${'first move only'.padStart(22)}  disagreement examples`);
for (const [motif, c] of [...ourTagCount.entries()].sort((a, b) => b[1].n - a[1].n)) {
	const f = firstTagCount.get(motif);
	const fCol = f ? `${String(f.n).padStart(4)}× ${pct(f.themed, f.n)}` : '—';
	console.log(
		`  ${motif.padEnd(18)} ${`${String(c.n).padStart(4)}× ${pct(c.themed, c.n)}`.padStart(16)} ${fCol.padStart(22)}  ${f?.examples.join(' ') ?? ''}`
	);
}

console.log('\nCOVERAGE (would explainGoodMove say anything about the first solver move?)');
console.log(`  overall: ${pct(firstTagged, total)} (${firstTagged}/${total})`);
console.log(`  puzzles with NO mapped theme: ${pct(unthemedButTagged, unthemedTotal)} (${unthemedButTagged}/${unthemedTotal}) still get a claim`);

console.log('\nGAP LIST — motif themes with no detector, by frequency in sample');
const covered = new Set(Object.keys(THEME_TO_MOTIF));
for (const [theme, n] of [...themeFreq.entries()].sort((a, b) => b[1] - a[1])) {
	if (META_THEMES.has(theme) || covered.has(theme)) continue;
	console.log(`  ${theme.padEnd(22)} ${String(n).padStart(4)}  (${((100 * n) / total).toFixed(1)}%)`);
}
