// Every baked icon, checked against what declares it.
//
// These files are generated (`python3 scripts/make-icons.py` from the repo
// root, master design/roboknight.png) and the failure mode is silent: one size
// regenerated by hand at the wrong dimension, an app icon that kept its alpha,
// or a "maskable" PWA icon that is a byte-for-byte copy of the plain one. None
// of that shows up in a file listing, a build, or a screenshot of the app —
// only in App Store validation, or in a launcher that crops the ears off.
//
// So the assertions here read the PNG header directly rather than trusting a
// filename, and take the expected sizes from the manifests that consume them
// (each Contents.json, web/manifest.json) rather than restating a list that
// could itself drift.
//
//   cd flutter && flutter test test/app_icons_test.dart

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';

/// The four PNG colour types we care about. iOS refuses alpha; macOS needs it.
const int _truecolour = 2; // RGB, no alpha
const int _truecolourAlpha = 6; // RGBA

class _Png {
  _Png(this.width, this.height, this.colourType);
  final int width;
  final int height;
  final int colourType;
}

/// Parse the IHDR only — enough for size and colour type, and it cannot be
/// fooled by a file that merely has the right name and length.
_Png _readPng(File f) {
  final bytes = f.readAsBytesSync();
  expect(bytes.length, greaterThan(33), reason: '${f.path} is too short to be a PNG');
  expect(bytes.sublist(0, 8), [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A],
      reason: '${f.path} is not a PNG');
  expect(String.fromCharCodes(bytes.sublist(12, 16)), 'IHDR',
      reason: '${f.path}: first chunk is not IHDR');
  final view = ByteData.sublistView(Uint8List.fromList(bytes));
  return _Png(view.getUint32(16), view.getUint32(20), view.getUint8(25));
}

/// filename -> pixel size, as the .appiconset itself declares it. Xcode allows
/// one file to serve several entries (app_icon_32.png is 16x16@2x and
/// 32x32@1x), which is fine as long as they agree on the pixels.
Map<String, int> _declaredSizes(File contents) {
  final images = (jsonDecode(contents.readAsStringSync()) as Map)['images'] as List;
  final sizes = <String, int>{};
  for (final image in images.cast<Map<String, dynamic>>()) {
    final name = image['filename'] as String?;
    if (name == null) continue;
    final pt = double.parse((image['size'] as String).split('x').first);
    final scale = double.parse((image['scale'] as String).replaceAll('x', ''));
    final px = (pt * scale).round();
    expect(sizes[name] ?? px, px, reason: '${contents.path}: $name is claimed at two sizes');
    sizes[name] = px;
  }
  expect(sizes, isNotEmpty, reason: '${contents.path} declares no images');
  return sizes;
}

void main() {
  group('iOS app icon', () {
    final dir = Directory('ios/Runner/Assets.xcassets/AppIcon.appiconset');

    test('every size Contents.json declares exists at exactly that size', () {
      final declared = _declaredSizes(File('${dir.path}/Contents.json'));
      expect(declared.length, 15, reason: 'the iOS set is 15 files; Contents.json changed');
      for (final entry in declared.entries) {
        final png = _readPng(File('${dir.path}/${entry.key}'));
        expect([png.width, png.height], [entry.value, entry.value],
            reason: '${entry.key} is ${png.width}x${png.height}, declared ${entry.value}');
      }
    });

    test('carries no alpha channel', () {
      // Not cosmetic: Xcode/App Store validation rejects an iOS icon with an
      // alpha channel outright, and where alpha survives it is composited onto
      // BLACK — which for a black glyph means an invisible icon.
      for (final f in dir.listSync().whereType<File>()) {
        if (!f.path.endsWith('.png')) continue;
        expect(_readPng(f).colourType, _truecolour,
            reason: '${f.path} is not opaque RGB');
      }
    });
  });

  group('macOS app icon', () {
    final dir = Directory('macos/Runner/Assets.xcassets/AppIcon.appiconset');

    test('every size Contents.json declares exists at exactly that size', () {
      final declared = _declaredSizes(File('${dir.path}/Contents.json'));
      for (final entry in declared.entries) {
        final png = _readPng(File('${dir.path}/${entry.key}'));
        expect([png.width, png.height], [entry.value, entry.value],
            reason: '${entry.key} is ${png.width}x${png.height}, declared ${entry.value}');
      }
    });

    test('keeps its alpha, because the Dock does not mask', () {
      // The opposite requirement to iOS. macOS shows the pixels given, so the
      // icon is a rounded plate in a transparent margin (Apple's 824-on-1024
      // grid); flattening it would put a square tile in a Dock of round ones.
      for (final f in dir.listSync().whereType<File>()) {
        if (!f.path.endsWith('.png')) continue;
        expect(_readPng(f).colourType, _truecolourAlpha,
            reason: '${f.path} lost its transparent margin');
      }
    });
  });

  group('web icons', () {
    final manifest =
        jsonDecode(File('web/manifest.json').readAsStringSync()) as Map<String, dynamic>;
    final icons = (manifest['icons'] as List).cast<Map<String, dynamic>>();

    test('every manifest entry exists at the size it advertises', () {
      expect(icons, isNotEmpty);
      for (final icon in icons) {
        final f = File('web/${icon['src']}');
        expect(f.existsSync(), isTrue, reason: '${icon['src']} is in the manifest but not on disk');
        final png = _readPng(f);
        final want = int.parse((icon['sizes'] as String).split('x').first);
        expect([png.width, png.height], [want, want],
            reason: '${icon['src']} is ${png.width}x${png.height}, advertised ${icon['sizes']}');
      }
    });

    test('the maskable icons are a different export, not the plain one renamed', () {
      // The regression this file was written for. Chrome will happily use a
      // full-bleed icon as maskable; the launcher then crops it to a circle
      // and takes the ears off. Identical bytes prove nobody re-exported.
      final maskable = icons.where((i) => (i['purpose'] as String?) == 'maskable').toList();
      expect(maskable.length, greaterThanOrEqualTo(1),
          reason: 'the manifest promises no maskable icon at all');
      for (final icon in maskable) {
        final size = (icon['sizes'] as String).split('x').first;
        final plain = File('web/icons/Icon-$size.png');
        final padded = File('web/${icon['src']}');
        expect(padded.readAsBytesSync(), isNot(plain.readAsBytesSync()),
            reason: '${icon['src']} is a copy of ${plain.path}');
      }
    });

    test('the favicon is a real PNG with no alpha', () {
      final png = _readPng(File('web/favicon.png'));
      expect(png.colourType, _truecolour);
      expect(png.width, png.height);
    });
  });

  group('the in-app mark', () {
    test('keeps its alpha, because ImageIcon tints through it', () {
      final png = _readPng(File('assets/roboknight.png'));
      expect(png.colourType, _truecolourAlpha,
          reason: 'flattened, this becomes a black square rather than a tinted glyph');
      expect([png.width, png.height], [128, 128]);
    });

    test('is bundled', () {
      // An asset that is not declared fails at runtime, in whatever screen
      // happens to show it, with an exception no test would otherwise catch.
      expect(File('pubspec.yaml').readAsStringSync(), contains('assets/roboknight.png'));
    });
  });
}
